title: "Healthume"
description: "Health and wellness tips, articles, and products"
url: ""          
baseurl: ""       
author:
  name: "Healthume"

layouts_dir: _layouts        
includes_dir: _includes     
collections_dir: _posts      
assets_dir: assets           


theme: minima                
plugins:
  - jekyll-feed
  - jekyll-seo-tag


markdown: kramdown
highlighter: rouge


permalink: /:title/  

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
